language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
branches:
  except:
    - image
sudo: required
before_install:
  - sudo apt-get remove redis-server -y
  - sudo apt-get clean -y
  - wget http://download.redis.io/releases/redis-3.2.8.tar.gz
  - tar xzf redis-3.2.8.tar.gz
  - cd redis-3.2.8
  - sudo make
  - sudo src/redis-server &
  - cd ..
